package net.mixed;

import java.util.ArrayList;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLLoadCompleteEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.mixed.proxy.CommonProxy;

@Mod(name = MixedCraft.MOD_NAME, modid = MixedCraft.MOD_ID, version = MixedCraft.MOD_VERSION)
public class MixedCraft {
	
	public static final String MOD_NAME = "Mixed Craft";
	public static final String MOD_ID = "mixed";
	public static final String PREFIX = MOD_ID + ":";
	public static final String MOD_VERSION = "1.0";

	public static final Logger LOGGER = LogManager.getLogger(MOD_NAME);

	public static CreativeTabs MTab = new CreativeTabs("mixed.tab") {

		@Override
		public ItemStack createIcon() {
			return new ItemStack(ItemHandler.FLASH_DRIVE);
		}
		
	};
	
	
	@Instance(MixedCraft.MOD_ID)
	public static MixedCraft instance;
	
	@SidedProxy(clientSide = "net.mixed.proxy.ClientProxy", serverSide = "net.mixed.proxy.CommonProxy")
	public static CommonProxy proxy;

	@EventHandler
	public static void preInit(FMLPreInitializationEvent event) {
		proxy.preInit(event);

		ArrayList<String> author = new ArrayList<>();
		author.add("The_SlayerMC");
		event.getModMetadata().autogenerated = false;
		event.getModMetadata().credits =
				"The_SlayerMC - Owner/Creator ";
		event.getModMetadata().modId = MixedCraft.MOD_ID;
		event.getModMetadata().url = "https://slayermods.net";
		event.getModMetadata().name = MixedCraft.MOD_NAME;
		event.getModMetadata().version = MixedCraft.MOD_VERSION;
		event.getModMetadata().logoFile = "assets/mixed/textures/logo.png";
		event.getModMetadata().authorList = author;
	}

	@EventHandler
	public static void init(FMLInitializationEvent event) {
		proxy.init(event);
	}

	@EventHandler
	public static void postInit(FMLPostInitializationEvent event) {
		proxy.postInit(event);
	}

	public static void onLoadComplete(FMLLoadCompleteEvent event) {
		proxy.onLoadComplete(event);
	}

	@EventHandler
	public static void serverStarting(FMLServerStartingEvent event) {
		proxy.serverStarting(event);
	}

	public static ResourceLocation rl(String path) {
		return new ResourceLocation(MixedCraft.MOD_ID, path);
	}
}
